version: "3.8"
services:
  influxdb:
    container_name: influxdb
    image: influxdb
    volumes:
      - data/influxdb:/var/lib/influxdb
      - conf/influxdb:/etc/influxdb/
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf
    volumes:
      - conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    
  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "0"
    ports:
      - "3000:3000"
    volumes:
      - data/grafana:/var/lib/grafana
      - log/grafana:/var/log/grafana
      - conf/grafana/grafana.ini:/etc/grafana/grafana.ini
    restart: always

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    user: "0"
    ports:
      - "8883:8883"
    volumes:
      - conf/mqtt/:/mosquitto/config/
      - data/mqtt/:/mosquitto/data/
      - log/mqtt/:/mosquitto/log/
      - cert/mqtt/:/mosquitto/cert/
    restart: always
