version: "3.8"
services:
  influxdb:
    container_name: influxdb
    image: influxdb
    volumes:
      - ./data/influxdb:/var/lib/influxdb
      - ./conf/influxdb:/etc/influxdb/
    deploy:
        restart_policy:
          condition: on-failure

  telegraf:
    container_name: telegraf
    image: telegraf
    volumes:
      - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
    
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./log/grafana:/var/log/grafana
      - ./conf/grafana/grafana.ini:/etc/grafana/grafana.ini
    deploy:
      restart_policy:
        condition: on-failure

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    ports:
      - "8883:8883"
    volumes:
      - ./conf/mqtt/:/mosquitto/config/
      - ./data/mqtt/:/mosquitto/data/
      - ./log/mqtt/:/mosquitto/log/
      - ./cert/mqtt/:/mosquitto/cert/
    deploy:
      restart_policy:
        condition: on-failure